### ISSUE TITLE
ghq import deprecated

### ISSUE THREAD

**Issue by mlavi** [klane/dotbot-ghq#1]
[ghq import](https://github.com/x-motemen/ghq/commit/991421b2afab8aa35edfb4ce7ed961a5a35dac7b) was dropped just before the new year (2020).

```
$ ghq --version
ghq version 1.1.0 (rev:057e0ff)
$ ghq import
No help topic for 'import'
```

Would it be possible to make a wrapper function around each line of ghqfile:file to do a ghq get instead? I can attempt a hack if desired!

**Comment by klane** [comment]
Thanks for your interest @mlavi. Since ghq dropped the import command, do you think the same should be done here? If you like the ability to specify repos in a separate file, it will be easy enough for me to pipe each line to `ghq get`.

**Comment by mlavi** [comment]
Yes please, I would like that. By refactoring the function, it prevents a need for the community who leverages dotbot-ghq to change their configuration or regress their use!

I do like the ability to externalize my repo list that I keep in heavy rotation for maintenance, otherwise I'd have to regularly update my dotbot intally.conf.yml file. That's certainly not a horrible thing for a fallback.

Anyhow, thank you for your consideration.

**Comment by klane** [comment]
Works for me. Relying only on `ghq get` should future proof this project as well, but I think I will add a GitHub Action to periodically test it just to be sure. I will try to make the change this weekend.

**Comment by klane** [comment]
@mlavi I finally got around to looking at this and discovered the functionality of `ghq import` still exists, it was just ported to `ghq get`. All that was required was changing the `ghq` command! Please let me know if you have any issues.

**Comment by mlavi** [comment]
Awesome, I'm sorry I didn't realize that on first glance.
